server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 100MB
  #数据库连接配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_informationshare?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    # 这个开发配置为false，避免改了模板还要重启服务器
    cache: false
  # QQ邮箱发送配置
  mail:
    # host不配置会注入失败
    host: smtp.qq.com
    #自己的邮箱
    username: 1203007469@qq.com
    #授权码
    password: aaaaaaaaaaaaaaaaaa
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          ssl:
            enable: true #一定要开启ssl,不然会503 验证失败的（开启加密验证）

#用户头像图片存储地址
userImageFilePath: C://Java/apache-tomcat-9.0.22-windows-x64/apache-tomcat-9.0.22-windows-x64/apache-tomcat-9.0.22/webapps/InformationSharing/static/images/userImage/
#文章图片存储地址
articleImageFilePath: C://Java/apache-tomcat-9.0.22-windows-x64/apache-tomcat-9.0.22-windows-x64/apache-tomcat-9.0.22/webapps/InformationSharing/static/images/articleImage/

#mybatis配置
mybatis:
  #配置SQL映射文件路径
  mapper-locations: classpath:mybatis/mapper/*.xml
  #配置别名
  type-aliases-package: com.ledao.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true